Repository ScribeLabsAI/ScribeMi, pull requests merged in 2023-11, with the labels that each got.

#115 fix: missing dependencies in setup.py
  scribemi/ScribeMi.py
  scribemi/__init__.py
  setup.py
  tests/test_scribemi.py
Labels: bug

#118 chore(master): release 1.3.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending

#133 Update deps
  requirements.txt
Labels: dependencies

#138 Update deps
  requirements.txt
Labels: dependencies
